# Generated by Django 3.2.4 on 2021-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
